import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const Roseritta = localFont({
  src: "../../public/fonts/Roseritta.otf",
  display: "swap",
  variable: "--font-roseritta",
});

const BDOGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/BDOGrotesk-Light.otf",
      weight: "300",
    },
    {
      path: "../../public/fonts/BDOGrotesk-Regular.otf",
      weight: "400",
    },
    {
      path: "../../public/fonts/BDOGrotesk-Medium.otf",
      weight: "500",
    },
    {
      path: "../../public/fonts/BDOGrotesk-ExtraBold.otf",
      weight: "700",
    },
  ],
  display: "swap",
  variable: "--font-bdo-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${BDOGrotesk.className} ${Roseritta.className}`}>
        {children}
      </body>
    </html>
  );
}
